parameters:
    - name: enable_python_master
      displayName: Test against Python master branch
      type: boolean
      default: false

pool:
    vmImage: 'ubuntu-18.04'

steps:
    - task: UsePythonVersion@0
      inputs:
          versionSpec: '>=3.5'
    - script: |
        set -x
        sudo apt update
        sudo apt install -y qemu-user git-lfs
        python -m pip install --upgrade pip
        pip install pytest wheel coverage
      displayName: Install dependencies

    - script: |
        git lfs pull
      displayName: Pull prebuilt binaries

    # This step is usually disabled. We only do this for our weekly builds, or
    # if it was specifically requested in a commit message
    - ${{ if or(eq(parameters.enable_python_master, true), eq(variables['Build.Reason'], 'Schedule')) }}:
      - script: |
          tar xf tests/prebuilt/prebuilt_musl_arm_aarch64.tar.xz
          ./tests/prebuilt/make_master.sh $PWD/prebuilt_musl_arm_aarch64/musl-toolchain
        displayName: Cross compile Python master branch

    - script: |
        pytest --junit-xml=test-results.xml --coverage
      displayName: Run tests

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: 'Publish test results'

    - script: |
        coverage combine
        coverage xml
      condition: succeededOrFailed()
      displayName: Collect code coverage

    - task: PublishCodeCoverageResults@1
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'

schedules:
    - cron: "0 12 * * 0"
      displayName: "Weekly build"
      branches:
          include:
              - master
      always: true
